version: '3.9'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: yarn start:dev
